name: Build and Push Docker Images
on:
   [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push backend image
        run: docker build -t ./api imranawsdevops/devops-qr-code-backend:latest 


      - name: push backend image
        
        run: |
            docker login -u imranawsdevops -p ${{ secrets.DOCKER_HUB_TOKEN }}
            docker push imranawsdevops/devops-qr-code-backend:latest
