name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t imranawsdevops/devops-qr-code-backend:latest ./api
          docker build -t imranawsdevops/devops-qr-code-frontend:latest ./front-end-nextjs/
      - name: push image to docker hub
        run: |
          docker login -u imranawsdevops -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push imranawsdevops/devops-qr-code-backend:latest
          docker push imranawsdevops/devops-qr-code-frontend:latest